name = "SyntaxInterface"
uuid = "b33eeca9-aacb-4496-a840-e75f1646a4fb"
authors = ["Willow Ahrens"]
version = "0.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.1"

[targets]
test = ["Test"]
